#!/bin/bash

source venv/Scripts/activate &&
rm db.sqlite3
rm -r recipes/migrations
rm -r users/migrations
python manage.py makemigrations users recipes api &&
python manage.py migrate &&
python manage.py shell -c "
from django.contrib.auth import get_user_model
User = get_user_model()
user=User.objects.create_user(
email='admin@support.com',
username='admin',
first_name='ad',
last_name='min',
password='verystr000ngpass!')
user.is_superuser=True
user.is_staff=True
user.save()" || exit 1


python manage.py runserver
